### ISSUE TITLE
Matplotlib NavigationToolbar

### ISSUE THREAD

**Issue by sgkang** [sgkang/PhysPropIP#2]
Can you figure out how to place the  at the top of the mplCole widget rather than the whole ZarcFitwidget?

**Comment by sgkang** [comment]
@RandyEnkin Not exactly sure what does this question means. Could you add bit more explanation?

**Comment by RandyEnkin** [comment]
This is a minor point that we should forget.  I was thinking the Matplotlib toolbar should be closer to the plots.  But it sits with the toolbar we will define for the whole window, so it uses the least real estate as is.
