### ISSUE TITLE
Can we rename rename Zarcfit.py to ZarcfitCalculations.py ?

### ISSUE THREAD

**Issue by sgkang** [sgkang/PhysPropIP#3]

**Comment by sgkang** [comment]
@RandyEnkin Not sure at the moment, because I want to optimization function in Zarcfit class, so Zarfit includes both forward and inverse

**Comment by RandyEnkin** [comment]
I am just worried about confusion with the main program, also called Zarcfit.  How about we call the file with the class ZarcSub

**Comment by sgkang** [comment]
Fixed
