### ISSUE TITLE
Filehandler: path

### ISSUE THREAD

**Issue by sgkang** [sgkang/PhysPropIP#4]
I have placed menu items at the top of the GUI, but I have not yet figured out how to attach them.  I see things like the following line to select a path:

path = str(QtGui.QFileDialog.getExistingDirectory(self, "Select Directory  "))

```
            but how do we attach it to “actionSelect_Path” ?
```

The file select slider is attached to the number select.  That was done completely in QtDesigner with the signal-slot method.

**Comment by RandyEnkin** [comment]
I have adapted a PyQt4 file picker program (http://www.eurion.net/python-snippets/snippet/File%20Picker.html) into a path picker.  It's called pathpicker.py .  If I can call it when you click on the Path option from the menu or toolbar, are you then able to read in all the files from that  path and choose the i'th file using the file selection slider or box?

**Comment by RandyEnkin** [comment]
OK, I have an extra GUI for the PathPicker, and a connection to the event: 
        ZarcFitWindow.actionSelect_Path.triggered.connect(PathPicker.show)
but I really don't know how to get that GUI to show and execute.  in the program PathPicker.py, the Main routine says:

# If the program is run directly or passed as an argument to the python

# interpreter then create a pathPicker instance and show it

if **name** == "**main**":
    app = QtGui.QApplication(sys.argv)
    gui = PathPicker()
    gui.show()
    app.exec_()

Assuming you can get the PathPicker to work, the file selector should be connected to ReadObsFile()
        ZarcFitWindow.spinBoxObsFileNumber.valueChanged.connect(ZarcFitWindow.ReadObsFile)

**Comment by RandyEnkin** [comment]
While the file selector slider valueChanged event is successfully triggered, I do not thing the PickPath event is ever triggerred.  I tried a different way this morning, but I don't believe the function is ever called because the print("PickPath") never shows up.  Any ideas?

**Comment by RandyEnkin** [comment]
PathPicker Window works!  Need something like
       ZarcFitWindow.lineEditPath.setText(fname)
in line 44.

So now, we need
1: The path written into ZarcFitWindow.lineEditPath
2: Read the directory of *.Z files into a table
3: Link the file selector slider to that table
3a: write the selected filename to ZarcFitWindow.lineEditObsFileName
3b: read in data from filename
3c: plot Obs data.

**Comment by sgkang** [comment]
Hi randy,

```
 Nice. I did first one. And I am playing with other items.
```

Seogi.

2015-11-18 22:19 GMT-08:00 RandyEnkin notifications@github.com:

**Comment by RandyEnkin** [comment]
```
                                                                                  ‎I have to go into QtDesigner and rename the lineEdit box to have a useful name like lineEditObsFileName. It will be done around 7:30 tomorrow morning.     Randy                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone on the Rogers network.                                                                                                                                                                                                                From: sgkangSent: Wednesday, November 18, 2015 10:31 PMTo: sgkang/PhysPropIPReply To: sgkang/PhysPropIPCc: RandyEnkinSubject: Re: [PhysPropIP] Filehandler: path (#4)Hi randy,

 Nice. I did first one. And I am playing with other items.
```

Seogi.

2015-11-18 22:19 GMT-08:00 RandyEnkin notifications@github.com:

> PathPicker Window works! Need something like
> ZarcFitWindow.lineEditPath.setText(fname)
> in line 44.
> 
> So now, we need
> 1: The path written into ZarcFitWindow.lineEditPath
> 2: Read the directory of *.Z files into a table
> 3: Link the file selector slider to that table
> 3a: write the selected filename to ZarcFitWindow.lineEditObsFileName
> 3b: read in data from filename
> 3c: plot Obs data.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sgkang/PhysPropIP/issues/4#issuecomment-157962373.

—Reply to this email directly or view it on GitHub.

**Comment by RandyEnkin** [comment]
Other than reading in the Parameter File, we have our file handling done!
